project:
  type: book
  output-dir: docs

book:
  title: "Happy Git and GitHub for the useR"
  #reader-mode: true

  page-footer:
    left: |
      Happy Git and GitHub for the useR was written by Jenny Bryan, the STAT 545 TAs, Jim Hester.
    right: |
      This book was built using <a href="https://quarto.org/">Quarto</a>.
#  cover-image: img/watch-me-diff-watch-me-rebase-smaller.png
#  favicon: projectlogo.png
  author:
    - name: Jenny Bryan
    - name: Jim Hester
    - name: STAT 545 TAs
  search: true
  # sidebar:
  #   pinned: true
  #   tools:
  #     - icon: github
  #       menu:
  #         - text: Original
  #           url: https://github.com/jennybc/happy-git-with-r
  #         - text: Traducción
  #           url: https://github.com/davidrsch/hgitwithres
  repo-url: https://github.com/jennybc/happy-git-with-r
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - overview.qmd
    - contributors.qmd
    - workshops.qmd
    - part: "Installation"
      chapters:
        - install-intro.qmd
        - install-github-acct.qmd
        - install-r-rstudio.qmd
        - install-git.qmd
        - install-introduce-self-git.qmd
        - install-git-client.qmd
    - part: "Connect Git, GitHub, RStudio"
      chapters:
        - connect-intro.qmd
        - connect-https-pat.qmd
        - connect-ssh-keys.qmd
        - connect-git-github.qmd
        - connect-rstudio-git-github.qmd
        - connect-can-rstudio-use-git.qmd
        - connect-troubleshooting.qmd
    - part: "Early GitHub Wins"
      chapters:
        - usage-intro.qmd
        - usage-new-project-github-first.qmd
        - usage-existing-project-github-first.qmd
        - usage-existing-project-github-last.qmd
        - usage-rmd-and-github.qmd
        - usage-r-script-and-github.qmd
    - part: "Git fundamentals"
      chapters:
        - git-intro.qmd
        - git-basics.qmd
        - git-commands.qmd
        - git-branches.qmd
        - git-remotes.qmd
        - git-refs.qmd
    - part: "Remote setups"
      chapters:
        - remote-setups-intro.qmd
        - remote-setups-common.qmd
        - remote-setups-equivocal.qmd
    - part: "Daily Workflows"
      chapters:
        - workflows-intro.qmd
        - workflows-repeated-amend.qmd
        - workflows-push-rejected.qmd
        - workflows-pull.qmd
        - workflows-see-the-past.qmd
        - workflows-fork-and-clone.qmd
        - workflows-upstream-changes-into-fork.qmd
        - workflows-explore-extend-pull-request.qmd
        - workflows-make-github-repo-browsable.qmd
    - part: "Activity prompts"
      chapters:
        - prompt-clone.qmd
        - prompt-fork-pr-bingo.qmd
        - prompt-burn-it-all-down.qmd
        - prompt-practice-resets.qmd
        - prompt-search-github.qmd
    - part: "Notes"
      chapters:
        - notes-intro.qmd
        - notes-classroom-overview.qmd
        - notes-ideas.qmd
        # - notes-bookdown-cheat-sheet.qmd
  appendices:
    - shell.qmd
    - comic-relief.qmd
    - resources.qmd
    - references.qmd
lang: en


format:
  html:
    theme:
      - cosmo
    #  - hopr.scss
    code-link: true
    bibliography: [book.bib, packages.bib]
    biblio-style: apalike
    link-citations: yes
    #author-meta: "Garrett Grolemund"
    callout-appearance: simple
    #include-after-body: [ddrsch_script.html]

editor: visual
