# ¿Puedes escucharme ahora? {#sec-connect-intro .unnumbered}

Los siguientes capítulos repasan algunas operaciones básicas para confirmar que ha instalado el software necesario y que se están realizando las conexiones necesarias, entre las herramientas de su computadora y entre su computadora y GitHub.

Esto se superpone mucho con algunos flujos de trabajo básicos que revisaremos más adelante, pero la segunda vez (o en un taller en vivo), dedicaremos más tiempo a explicar qué está sucediendo y por qué.

Desafortunadamente, tenemos que adelantar una tarea bastante complicada, que es decidir si comunicarnos con GitHub a través de HTTPS o SSH y configurar algunas credenciales en consecuencia. En [Token de acceso personal para HTTPS](#sec-https-pat) analizamos cómo elegir entre HTTPS y SSH y luego explicamos cómo obtener un token de acceso personal, que se usa con HTTPS. O, alternativamente, te ayudaremos a [Configurar claves para SSH](#sec-ssh-keys).

Una vez que tenemos nuestras credenciales ordenadas, en [Conectar a GitHub](#sec-push-pull-github), usamos Git en el shell para asegurarnos de que pueda clonar un repositorio desde GitHub y establecer comunicaciones bidireccionales, es decir, importar y enviar.

En [Conectar RStudio a Git y GitHub](#sec-rstudio-git-github) confirmamos que RStudio puede trabajar con su instalación de Git para realizar operaciones locales y comunicarse con GitHub.

Esperemos que no lo necesites, pero esta parte concluye con dos capítulos de solución de problemas: [Detectar Git desde RStudio](#sec-rstudio-see-git) y [RStudio, Git, GitHub Hell](#sec-troubleshooting).
