# Algunos conceptos básicos de Git {#sec-git-intro .unnumbered}

¡Hasta ahora te hemos contado sorprendentemente poco sobre Git! Esto es por diseño.

Descubrimos que el uso real, en el curso de su trabajo, es la forma más efectiva de construir un modelo mental útil para Git. En los talleres en vivo, nos esforzamos por presentar las ideas básicas más importantes en el contexto de nuestras actividades guiadas. Los autodidactas pueden lograr lo mismo si siguen las guías sobre "pilas incluidas" que aparecen anteriormente en las secciones anteriores.

Sin embargo, aprovechando este éxito inicial, ahora es el momento perfecto para definir explícitamente algo de vocabulario de Git. También queremos ayudarlo a vincular los conceptos de Git con tareas y proyectos de ciencia de datos.

Esta parte recopila todo lo que hemos escrito sobre los conceptos básicos de Git. Es un trabajo en progreso y está concebido como un complemento a los excelentes [recursos externos para Git](#sec-resources), que no tenemos ningún deseo de reinventar.
