# Comandos de git {#sec-git-commands}

Una colección de algunos de los comandos de Git que se han estado ejecutando en gran medida bajo el capó. Hemos enfatizado los primeros flujos de trabajo que son posibles en RStudio. Pero todo esto y mucho más se puede hacer desde la línea de comandos. Esta lista está aquí principalmente para que podamos consultarla durante los talleres en vivo si es necesario.

*A menos que utilice la [API de GitHub](https://developer.github.com/v3/), la mayoría de los bits de GitHub realmente deben realizarse desde el navegador.*

Nuevo repositorio de git local desde un repositorio en GitHub:

``` console
git clone https://github.com/jennybc/happy-git-with-r.git
```

Verifique que el control remoto se haya clonado exitosamente:

``` console
git remote --verbose
```

Seleccionar cambios locales, confirmar:

``` console
git add foo.txt
git commit --message "Un mensaje de confirmación"
```

Compruebe el estado del mundo Git:

``` console
git status
git log
git log --oneline
```

Comparar versiones:

``` console
git diff
```

Agregue un control remoto al repositorio local existente:

``` console
git remote add origin https://github.com/jennybc/happy-git-with-r
git remote --verbose
git remote show origin
```

Envíe el `main` local a GitHub `main` y haga que el `main` local rastree `main` en GitHub:

``` console
git push --set-upstream origin main
# forma más corta
git push -u origin main
# ¡solo necesitas configurar el seguimiento ascendente una vez!
```

Envío regular:

``` console
git push 
# lo anterior generalmente implica (y ciertamente lo hace en nuestro tutorial)
git push origin main
# git push [remote-name] [branch-name]
```

Importar confirmaciones desde GitHub:

``` console
git pull
```

Importar confirmaciones y no evitar que esto le ponga en un aprieto de conflicto de fusión:

``` console
git pull --ff-only
```

Obtener confirmaciones

``` console
git fetch
```

Cambiar a una rama

``` console
git checkout [branch-name]
```

Comprobación del seguimiento remoto y de ramas

``` console
git remote -v
git remote show origin
git branch -vv
```
