# Crear una cuenta de GitHub {#sec-github-acct}

Crear una cuenta con GitHub. ¡Es gratis!

-   <https://github.com>

## Consejos de nombre de usuario

Podrás actualizar a un nivel de servicio pago, aplicar descuentos, unirte a organizaciones, etc. en el futuro, así que no te preocupes por nada de eso ahora. **Excepto tu nombre de usuario. Tal vez quieras pensarlo un poco.**

Algunos consejos que lamentablemente tienden a contradecirse:

-   ¡Incorpora tu nombre real! A la gente le gusta saber con quién están tratando. También hace que su nombre de usuario sea más fácil de adivinar o recordar.
-   Reutiliza tu nombre de usuario de otros contextos, por ejemplo, Twitter o Slack. Pero, por supuesto, alguien sin actividad en GitHub probablemente estará ocupado con eso.
-   Elija un nombre de usuario que le resulte cómodo revelarle a su futuro jefe.
-   Más corto es mejor que más largo.
-   Ser lo más único posible en la menor cantidad de caracteres posible. En algunas configuraciones, GitHub completa automáticamente o sugiere nombres de usuario.
-   Hazlo atemporal. No resalte su universidad, empleador o lugar de residencia actual, p.ejemplo JennySeLaCuadra.
-   Evite palabras cargadas de significado especial en programación. En mis primeros esfuerzos ineptos para crear scripts en torno a la API de GitHub, le asigné muchos problemas a [el tipo con el nombre de usuario `NA`](https://github.com/na) porque mi vector de nombres de usuarios de GitHub contenía valores faltantes. Una variante de [Little Bobby Tables](https://xkcd.com/327/).
-   Evite el uso de mayúsculas y minúsculas para separar palabras. Recomendamos encarecidamente todo en minúsculas. GitHub trata los nombres de usuario sin distinguir entre mayúsculas y minúsculas, pero usar todas las minúsculas es más amable con las personas que realizan trabajos de expresión regular posteriores con nombres de usuarios, en varios idiomas. Una mejor estrategia para la separación de palabras es utilizar un guión `-`.

Puedes cambiar tu nombre de usuario más tarde, pero es mejor hacerlo bien la primera vez.

-   <https://help.github.com/articles/changing-your-github-username/>
-   <https://help.github.com/articles/what-happens-when-i-change-my-username/>

## Repositorios privados gratuitos

GitHub ofrece repositorios privados ilimitados y gratuitos para todos los usuarios. Estos repositorios privados gratuitos admiten hasta tres colaboradores externos, lo que los convierte en un lugar perfecto para sus proyectos personales, para solicitudes de empleo y para probar cosas antes de convertir su proyecto en código abierto.

Continúe y registre su cuenta gratuita AHORA y luego busque cualquier oferta especial que se aplique a usted:

-   Estudiantes, profesores y personal educativo/investigador: [GitHub Education](https://education.github.com).
    -   GitHub "Organizations" puede ser extremadamente útil para cursos o grupos de investigación/laboratorio, donde se necesita cierta coordinación entre un conjunto de repositorios y usuarios.
-   Organizaciones oficiales sin fines de lucro y organizaciones benéficas: [GitHub for Good](https://github.com/nonprofit)

## Pagar por repositorios privados

Cualquiera puede pagar para tener repositorios privados con soporte para colaboradores ilimitados. Un plan personal con repositorios privados que admite colaboradores ilimitados cuesta $ 7 por mes al momento de escribir este artículo e incluye varias [funciones avanzadas] (https://help.github.com/articles/github-s-products/#github-pro ). Vea los planes y precios actuales aquí:

-   <https://github.com/pricing>

Continúe y registre su cuenta gratuita AHORA. Podrás decidir más adelante si deseas actualizar a un plan pago.
