# La mitad de la batalla {#sec-install-intro .unnumbered}

Honestamente, instalar, configurar y ejecutar todo el software necesario en conjunto es la mitad de la batalla cuando se adopta Git por primera vez. Prepárate para un poco de dolor. La ventaja es que puedes darte una palmadita en la espalda una vez que superes esto. Y superarás esto.

Encontrará muchos más recursos sobre cómo *usar Git* que para la instalación y configuración. ¿Por qué? Los expertos ...

-   Llevan años haciendo esto. Simplemente ya no les resulta difícil.
-   Probablemente usen alguna versión de Unix. Es posible que en secreto (o no tan secretamente) se enorgullezcan de no usar ni conocer Windows.
-   Obtengan más satisfacción y recompensa por pensar y escribir sobre conceptos y flujos de trabajo de Git que por la instalación de Git.

En su defensa, es difícil escribir instrucciones de instalación. Las fallas pueden ser específicas de un sistema operativo individual o incluso de una computadora individual. Si tienes algún problema nuevo y, especialmente, la solución correspondiente, [¡nos encantaría saber de ti!](https://github.com/jennybc/happy-git-with-r/issues)

## Éxito y sistemas operativos.

```{=html}
<style type="text/css">
#success-and-operating-systems table {
  width: auto;
}
</style>
```
Nuestras instrucciones de instalación han sido forjadas en los fuegos de [STAT 545](http://stat545.com), [STAT 540](https://stat540-ubc.github.io), y talleres variados, durante varios años. Regularmente escuchamos de [almas agradecidas](https://twitter.com/ibddoctor/status/777610645617475584) [en internet](https://twitter.com/millsGT49/status/647059167509921793) que también han tenido éxito.

Aquí hay datos sobre los sistemas operativos que encontramos en STAT 545 y otros talleres: en general, la mayor parte se divide en partes iguales entre Mac y Windows (varios sabores), con una pizca de Linux. Excepto en el contexto de BioConductor (CSAMA), que está dominado por Mac o Linux.

|              |     2014 |     2015 |     2016 | useR! 2016 | CSAMA 2016 | CSAMA 2017 | r::c 2018 | seattle 2018 |
|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|
|          Mac | 16 (41%) | 38 (52%) | 37 (45%) |   28 (44%) |   25 (58%) |   23 (56%) |  51 (57%) |     16 (49%) |
| Windows 10\* |   0 (0%) |  8 (11%) | 30 (36%) |   27 (43%) |    6 (14%) |    8 (20%) |  19 (21%) |     12 (36%) |
|    Windows 8 | 12 (31%) |  9 (12%) |   4 (5%) |            |            |    1 ( 2%) |    2 (2%) |              |
|    Windows 7 |  9 (23%) | 13 (18%) | 10 (12%) |            |            |    1 ( 2%) |  13 (14%) |      4 (12%) |
|        Linux |   2 (5%) |   5 (7%) |   2 (2%) |    8 (13%) |   12 (28%) |    9 (20%) |    5 (6%) |       1 (3%) |

\* Windows 10 es el cajón de sastre de Windows, cuando no tengo información más específica.
