# Ideas para contenido

## Preguntas comunes sobre el flujo de trabajo

### Situaciones comunes y cómo recuperarlas/evitarlas

https://twitter.com/JennyBryan/status/743457387730735104

### Mantener algo fuera de Git

Listarlo en `.gitignore.`

### No quise cometer eso

Cometer cosas que no era tu intención (demasiado grandes, secretas). Cómo deshacer.

## git stuff

Git explicadores, pesados en los diagramas

https://twitter.com/JennyBryan/status/743548245645791232

Una referencia visual de Git\
http://marklodato.github.io/visual-git-guide/index-en.html

Un modelo de ramificación de Git exitoso\
http://nvie.com/posts/a-successful-git-branching-model/

Un modelo exitoso de ramificación de Git se considera dañino\
https://barro.github.io/2016/02/a-succesful-git-branching-model-considered-harmful/

Tutoriales de Git de Atlassian https://www.atlassian.com/git/tutorials/

Lección para principiantes de software de carpintería Git\
http://swcarpentry.github.io/git-novice/

Michael Freeman se desliza sobre la colaboración con Git\
http://slides.com/michaelfreeman/git-collaboration#/

Materiales de formación de GitHub\
https://services.github.com/kit/

Git para mayores de 4 años\
<https://www.youtube.com/watch?v=3m7BgIvC-uQ>

Aprenda la ramificación de Git\
http://learngitbranching.js.org

Una serie de tutoriales sobre el flujo de trabajo de Git http://vallandingham.me/git-workflow.html

-   Parte 1: Ramas de funciones
-   Parte 2: Revisión de solicitudes de extracción
-   Parte 3: Revisión de solicitudes de extracción localmente
-   Parte 4: Fusionar solicitudes de extracción

Git desde adentro hacia afuera\
https://codewords.recurse.com/issues/two/git-from-the-inside-out

## Recuperación ante desastres

<http://stackoverflow.com/questions?sort=votes>

Desglosarlo:

-   ¿Hay algún problema con mi sistema de archivos/archivos?
-   ¿Mi repositorio de git está en mal estado?
-   ¿Cómo puedo evitar que esto vuelva a suceder?

Técnicas para evitar rebases.

Estado sin cabeza. Infierno rebase.

Qué hacer cuando no puedes, por ejemplo, cambiar de rama. Confirmaciones de Trabajo en Proceso.

## Interactúe con el código fuente de R en GitHub

Interactúe con la fuente R en GitHub

Hojeada

Búsqueda

-   Mi esencia, re: el usuario de cran: <https://gist.github.com/jennybc/4a1bf4e9e1bb3a0a9b56>

Ser un usuario útil

-   manténgase informado sobre: desarrollo
-   use problemas para informes de errores, solicitudes de funciones
-   hacer solicitudes de extracción

## Flujo de trabajo y psicología

Estrés de trabajar al aire libre

Flujos de trabajo para grupo de 1, 2, 5, 10

-   Bifurcación y extracción frente a repositorio compartido

    -   <https://help.github.com/articles/about-collaborative-development-models/>
    -   <https://help.github.com/articles/using-pull-requests/>
