# Crear un cartón de bingo {#sec-bingo}

Aquí hay una sugerencia específica para practicar "bifurcar e importar".

El flujo de trabajo general se establece en @sec-fork-and-clone.

Jenny y Dean tienen un repositorio que fabrica cartones de bingo con R:

-   <https://github.com/jennybc/bingo>
-   ¡Lea el archivo README para obtener más información al respecto!

Tu misión:

-   ¿Quizás encontrar un socio? ¿O un par de socios?
-   Bifurcar el repositorio `bingo`.
-   Clonarlo en la máquina local de alguien.
-   Crear un nuevo cartón de bingo haciendo un archivo de posibles casillas.
    -   Siga las instrucciones en <https://github.com/jennybc/bingo/blob/master/CONTRIBUTING.md> para ver cómo contribuir con una nueva tarjeta.
    -   Consejo profesional: es fácil ser muy divertido, pero crea un cartón de bingo muy difícil. Recuerde incluir algunas cosas fáciles para que la gente tenga la oportunidad de jugar al bingo.
-   Si se siente virtuoso, ejecute las pruebas y revise el paquete. ¡Pídenos ayuda! O vivir peligrosamente y evitar esto.
-   ¡Comprometerse!
-   Vuelva a enviar sus cambios a su copia del repositorio en GitHub.
-   Realizar una solicitud de extracción al repositorio principal de "bingo".
-   Si su tarjeta es apropiada, fusionaremos su solicitud y pasará a formar parte del paquete y estará disponible a través de la [aplicación Shiny](http://daattali.com/shiny/bingo/).

**Inspiración especial para su uso**:

-   Haga bingo de conferencias específico para useR.
-   ¡Consulte este hilo temático para conocer muchas ideas cuadradas!
    -   <https://github.com/jennybc/bingo/issues/4>
