# Restablecer {#sec-reset}

Practica recuperarte de los errores.

Utilice un repositorio que haya creado anteriormente en el tutorial para esto. Solo necesita ser local, es decir, esto no involucra a GitHub.

Si no es su compromiso más reciente, considere seriamente dejarlo pasar. Justo. Dejar. Él. Ir.

¿Entonces quieres deshacer la última confirmación?

Si "SÍ, DESHAGALO COMPLETAMENTE": `git reset --hard HEAD^`. ¡Perderá cualquier cambio que no se haya reflejado en la última confirmación!

Si "SÍ, deshaga la confirmación, pero deje los archivos en ese estado (pero sin preparar)": `git reset HEAD^`. Sus archivos seguirán siendo los mismos, pero la confirmación se deshará y no se preparará nada.

Si "SÍ, regrese al momento anterior a mi compromiso": `git reset --soft HEAD^`. Sus archivos permanecerán igual pero la confirmación se deshará. Incluso se restaurarán los cambios realizados.

**Si solo desea modificar la confirmación más reciente o su mensaje, puede modificarlo. ¡Puedes hacer esto desde RStudio!**

-   Realice el cambio que desee y modifique el compromiso.
- ¿Quieres cambiar sólo el mensaje de confirmación?
    -   Haz otro pequeño cambio. ¿Seguramente tienes un error tipográfico en alguna parte? Modifique la confirmación, lo que le brinda la oportunidad de editar el mensaje.

Para modificar desde la línea de comando, usando un editor para crear el mensaje:

``` bash
git commit --amend
```

Para modificar desde la línea de comando, proporcionando el nuevo mensaje:

``` bash
git commit --amend -m "New commit message"
```

Restablecimiento de Git desmitificado:

<https://git-scm.com/book/en/v2/Git-Tools-Reset-Demystified>
