# Buscar en GitHub {#sec-search}

## Recursos básicos

Búsqueda en GitHub

-   <https://github.com/search/advanced>
-   <https://help.github.com/articles/searching-code/>
-   <https://help.github.com/articles/search-syntax/>

Espejo de solo lectura de la fuente R de Winston Chang:

-   <https://github.com/wch/r-source>

Espejo de solo lectura de todos los paquetes en CRAN por Gábor Csárdi:

-   <https://github.com/cran>
-   <http://cran.github.io>
-   [METACRAN](http://www.r-pkg.org)

## Caso de uso

¿Qué pasa si una función en un paquete no tiene ejemplos? ¿O está mal ejemplificado? ¿No sería bueno encontrar ejemplos funcionales de esto "en la naturaleza"?

[Via Twitter](https://twitter.com/noamross/status/563422536633839617), Noam Ross me enseñó una forma inteligente de realizar este tipo de búsquedas en GitHub. Coloque esto en el cuadro de búsqueda de GitHub para ver cómo los paquetes en CRAN usan la función `llply()` de `plyr`:

``` bash
"llply" user:cran language:R
```

O simplemente [haga clic aquí](https://github.com/search?l=r&q=%22llply%22+user%3Acran+language%3AR&ref=searchresults&type=Code).

Otro ejemplo que apareció recientemente en r-package-devel:

¿Cómo ver muchos ejemplos de plantillas de roxygen?

Esta búsqueda encuentra \>1400 ejemplos de plantillas de roxygen en la naturaleza:

<https://github.com/search?q=man-roxygen+in%3Apath&type=Code&ref=searchresults>
