# Clonar un repositorio {#sec-clone}

Clona el repositorio de otra persona en GitHub donde solo quieres una copia. Pero también quieres seguir su evolución. Eso es lo que diferencia un clon de GitHub de, digamos, simplemente descargar el archivo ZIP en un momento específico.

Elija un repositorio de GitHub que le interese. Inspiración:

-   un paquete R que te interesa
-   un proyecto de análisis de datos que le parezca interesante
    -   Ejemplo: el repositorio de GitHub que sustenta [la publicación del blog de Polygraphing](http://polygraph.cool/films/) que analiza 2000 guiones está aquí: <https://github.com/brandles/scripts>
    -   Ejemplo: FiveThirtyEight compartió los datos y el código detrás de su proyecto [Gun Deaths in America](http://fivethirtyeight.com/gun-deaths/) en GitHub: <https://github.com/fivethirtyeight/guns-data>. Eche un vistazo también a sus otros repositorios.

Cree un nuevo proyecto RStudio desde este repositorio de GitHub. Refresque su memoria sobre cómo hacerlo volviendo a visitar nuestro flujo de trabajo "GitHub primero" en @sec-new-github-first.

Una vez que tenga el código localmente, intente ejecutar parte del mismo. Intenta entender cómo funciona.

¿Quieres hacer un cambio? ¡Bien, haz eso!

¿Quieres enviar los cambios al autor original? Ahora sabes de primera mano cuándo debes *bifurcar en lugar de clonar*. Ver @sec-fork-and-clone.
