# Recursos {#sec-resources}

¡Practicamos lo que predicamos! Este sitio está creado con Git y R Markdown, utilizando el paquete [`bookdown`](https://github.com/rstudio/bookdown/). Continúe y [eche un vistazo detrás de escena](https://github.com/jennybc/happy-git-with-r).

A largo plazo, debería comprender más lo que está haciendo. Hacer clic de memoria en RStudio puede ser un método de supervivencia a corto plazo, pero no funcionará por mucho tiempo.

-   [Git for Humans](https://speakerdeck.com/alicebartlett/git-for-humans) es un gran conjunto de diapositivas de [Alice Bartlett](https://alicebartlett.co.uk), presentadas originalmente en 2016 en UX Brighton.

-   [Git in Practice](https://www.manning.com/books/git-in-practice) de Mike McQuaid es un libro más accesible, probablemente mejor que Pro Git (a continuación) para la mayoría de las personas que comienzan. Materiales auxiliares [en GitHub](https://github.com/MikeMcQuaid/GitInPractice).

-   El libro [Pro Git](http://git-scm.com/book) es fantástico y completo.

-   [Oh My Git!](https://ohmygit.org/) es un juego interactivo gratuito y de código abierto para aprender Git. Es muy amigable para principiantes y utiliza un gráfico para visualizar el árbol de trabajo. Las lecciones se pueden completar usando una interfaz de naipes además de la línea de comando incorporada, que está ahí para cuando los usuarios se sientan más cómodos..

-   [Los propios materiales de capacitación de GitHub](https://training.github.com) pueden resultar útiles. También señalan [muchos otros recursos](https://help.github.com/articles/what-are-other-good-resources-for-learning-git-and-github)

-   Busque un cliente Git potente (@sec-git-client) si desea minimizar el uso de Git desde la línea de comandos.

-   Diez reglas simples para aprovechar Git y GitHub <http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1004947>

-   Guía de RStudio [Control de versiones con Git y SVN](https://support.rstudio.com/hc/en-us/articles/200532077-Version-Control-with-Git-and-SVN)

-   El libro [*Team Geek*](http://shop.oreilly.com/product/0636920018025.do) tiene consejos interesantes para los aspectos humanos y colaborativos del control de versiones. Propone estrategias de Git adaptadas a diferentes características de los equipos.
