# Comience con GitHub {#sec-usage-intro .unnumbered}

Ahora que hemos verificado su configuración de Git/GitHub/RStudio, podemos hacer una demostración de los flujos de trabajo que usará para llevar su trabajo a GitHub:

-   [Nuevo proyecto, GitHub primero](#sec-new-github-first) es la forma más fácil de conseguir un proyecto funcional.
-   [Proyecto existente, GitHub primero](#sec-existing-github-first) es una forma profundamente pragmática de llevar trabajos preexistentes a GitHub.
-   [Proyecto existente, GitHub último](#sec-existing-github-last) es la forma más adecuada de conectar el trabajo local existente a un control remoto en GitHub, especialmente si ya existe un historial de Git.

Esta parte concluye con dos flujos de trabajo específicos de R que muestran qué tan bien [R Markdown (el formato)](https://rmarkdown.rstudio.com) y [rmarkdown (el paquete)](https://cran.r- project.org/package=rmarkdown) trabajan con GitHub:

-   [Prueba R Markdown](#sec-rmd-test-drive)
-   [Renderizar un script R](#sec-r-test-drive)
