# Talleres de trabajo

Estos materiales se pueden utilizar para el estudio independiente, pero también se han utilizado como apoyo:

-   talleres de trabajo en persona (vea abajo)
-   [STAT 545](http://stat545.com) en UBC
-   [UBC Máster en Ciencia de Datos](http://masterdatascience.science.ubc.ca)

## Configuración previa al taller

Lectura opcional sobre la motivación general: [¿Por qué Git?](#sec-big-picture)

**Es vital que intente configurar su sistema con anticipación. ¡No puedes presentarte al taller sin preparación y seguir al día!**

Prueba esto. En el mejor de los casos, es de aproximadamente 1 a 2 horas. Si choca contra una pared, le ayudaremos:

-   [Registre una cuenta de GitHub gratuita](#sec-github-acct).
-   [Instalar o actualizar R y RStudio](#sec-install-r-rstudio).
-   [Instalar Git](#sec-install-git).
-   [Preséntate a Git](#sec-hello-git).
-   [Configurar un token de acceso personal](#sec-https-pat) o [configure claves SSH](#sec-ssh-keys).
-   [Pruebe si Git local puede comunicarse con GitHub](#sec-push-pull-github).
-   [Pruebe que RStudio puede encontrar Git local](#sec-rstudio-git-github) y, por lo tanto, puede hablar con GitHub.
    -   Para su información: aquí es donde normalmente comienzan nuestras actividades prácticas. Recorremos juntos una actividad similar, con narrativa, y construimos a partir de ahí.
-   Considere si desea [instalar un cliente Git opcional](#sec-git-client), ahora o en el futuro.

Solución de problemas:

-   A veces RStudio [necesita un poco de ayuda para encontrar Git](#sec-rstudio-see-git).
-   Solución de problemas generales: [RStudio, Git, GitHub Hell](#sec-troubleshooting).

Estas son instrucciones probadas en batalla, por lo que la mayoría tendrá éxito. ¡Creemos en ti! Si tiene problemas, busque ayuda y siga adelante. Dónde obtener ayuda:

-   Si está inscrito en un próximo taller, encuéntrelo a continuación para obtener detalles sobre el soporte previo al taller.
-   *Podríamos* poder responder a un problema de GitHub [aquí](https://github.com/jennybc/happy-git-with-r/issues).
-   Si hay un ángulo claro de R/RStudio, publíquelo en <https://forum.posit.co/>.
-   Consejo general: busque en Google y en <https://stackoverflow.com>, consulte también <https://github.community>.

## posit::conf 2023

Taller de 1 día: Lo que olvidaron enseñarte sobre R\
Tendrá cobertura de medio día de Git/GitHub el 17 de septiembre, [`posit.co/conference`](https://posit.co/conference/) Día del taller, Chicago

Los participantes registrados en el taller deben utilizar [este hilo](https://forum.posit.co/t/what-they-forgot-to-teach-you-about-r-workshop-rstudio-conf-2022/138999) en forum.posit.co para analizar los problemas de preparación del sistema.

## Talleres anteriores

-   rstudio::conf 2022
-   Taller de 2 días: Lo que olvidaron enseñarte sobre R\
-   \~25% del contenido era Git/GitHub
-   25 y 26 de julio de 2022, Washington, D.C.
-   RaukR: Escuela de Verano de R Avanzado para Bioinformática
    -   13 de junio de 2022, en línea
-   rstudio::conf 2020
    -   Taller de 2 días: Lo que olvidaron enseñarte sobre R\
    -   \~25% del contenido era Git/GitHub + R/Rmd/RStudio\
    -   27 y 28 de enero de 2020, San Francisco, California
-   UBC Programa de Maestría en Ciencia de Datos
    -   Conferencia invitada sobre los flujos de trabajo diarios de Git/GitHub
    -   9 de enero de 2020
-   RaukR: Escuela de verano de R avanzado para bioinformática
    -   10-20 de junio de 2019, Visby, Suecia
-   rstudio::conf 2019
    -   Taller de 2 días: Lo que olvidaron enseñarte sobre R\
    -   \~25% del contenido era Git/GitHub + R/Rmd/RStudio\
    -   15 y 16 de enero de 2019, Austin, TX
-   Seattle Octubre 2018
    -   Taller de 2 días: [Lo que olvidaron enseñarte sobre R](https://whattheyforgot.org/index.html#seattle-2018-october-4-5)\
    -   3 de 8 unidades en Git/GitHub + R/Rmd/RStudio\
    -   4 y 5 de octubre de 2018, The Westin Seattle
-   rstudio::conf 2018
    -   Taller de 2 días: Lo que olvidaron enseñarte sobre R\
    -   \~25% del contenido era Git/GitHub + R/Rmd/RStudio\
    -   31 de enero y 1 de febrero de 2018, San Diego, CA
-   CSAMA 2017: Análisis de datos estadísticos para la biología del genoma
    -   <http://www.huber.embl.de/csama2017/>\
    -   11-16 de junio de 2017, Bressanone-Brixen, Italia\
-   Ciudad del Cabo 2017
    -   <http://capetown2017.satrdays.org>\
    -   16 al 18 de febrero de 2017, Ciudad del Cabo, Sudáfrica
-   rstudio::conf 2017
    -   <https://posit.co/conference/>\
    -   13 - 14 de enero de 2017, Orlando, FL\
    -   Sábado 14 de enero de 10:15 a 12:30
-   CSAMA 2016: Análisis de datos estadísticos para la biología del genoma
    -   <http://www.huber.embl.de/csama2016/>\
    -   10 - 15 de julio de 2016, Bressanone-Brixen, Italia\
-   useR! 2016 Stanford
    -   <http://user2016.r-project.org>\
    -   Lunes, 27 de junio de 2016\
    -   [Using Git and GitHub with R, RStudio, and R Markdown](http://user2016.r-project.org/tutorials/01.html)
