# Patrones de Git útiles para la vida real {#sec-workflows-intro .unnumbered}

*Gran parte de esto se origina como materiales de talleres en vivo; Los flujos de trabajo no vinculados están planificados pero aún no convertidos a prosa aquí..*

Patrones de Git que aparecen con frecuencia en el trabajo real:

-   Comprométete temprano y con frecuencia. Empuje con menos frecuencia. [Enmiendar repetidamente](#sec-repeated-amend).
-   [¡Ayuda, mi push fue rechazado!](#sec-push-rejected)
-   [Integrando el trabajo remoto y local](#sec-pull-tricky). Probablemente para que puedas enviar de nuevo.
-   Quémalo todo.
-   Viaje en el tiempo:
    -   ["Solo necesito ver el pasado".](#sec-time-travel-see-past) Navega y busca en GitHub.
    -   "Necesito visitar el pasado". Crea una caja en una sucursal.
    -   "Quiero volver al pasado". `git revert`, `git reset`
    -   "Comí una gran galleta en octubre pasado.". `git cherry pick`, `git checkout REF -- path`

Juega bien con los demás:

-   [Bifurca y clona](#sec-fork-and-clone).
-   [Obtener los cambios en upstream para una bifurcación](#sec-upstream-changes).
-   Bifurcación desechable.
-   [Haz que tu repositorio sea gratificante para navegar en GitHub](#sec-workflows-browsability).
-   [Explorar y ampliar una solicitud de cambio](#sec-pr-extend)
